In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Lasso, Ridge,ElasticNet
from sklearn.tree import  DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split,cross_val_score,GridSearchCV
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.pipeline import Pipeline
import plotly.graph_objects as go
# import xgboost as xgb
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('./Admission_Predict_Ver1.1.csv')
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [3]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   serial_no.         500 non-null    int64  
 1   gre_score          500 non-null    int64  
 2   toefl_score        500 non-null    int64  
 3   university_rating  500 non-null    int64  
 4   sop                500 non-null    float64
 5   lor                500 non-null    float64
 6   cgpa               500 non-null    float64
 7   research           500 non-null    int64  
 8   chance_of_admit    500 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB


In [5]:
df.drop('serial_no.',axis=1,inplace=True)

In [6]:
df.head()

gre_score  toefl_score  university_rating  sop  lor  cgpa  research  \
0        337          118                  4  4.5  4.5  9.65         1   
1        324          107                  4  4.0  4.5  8.87         1   
2        316          104                  3  3.0  3.5  8.00         1   
3        322          110                  3  3.5  2.5  8.67         1   
4        314          103                  2  2.0  3.0  8.21         0   

   chance_of_admit  
0             0.92  
1             0.76  
2             0.72  
3             0.80  
4             0.65

In [7]:
df.describe()

gre_score  toefl_score  university_rating         sop        lor  \
count  500.000000   500.000000         500.000000  500.000000  500.00000   
mean   316.472000   107.192000           3.114000    3.374000    3.48400   
std     11.295148     6.081868           1.143512    0.991004    0.92545   
min    290.000000    92.000000           1.000000    1.000000    1.00000   
25%    308.000000   103.000000           2.000000    2.500000    3.00000   
50%    317.000000   107.000000           3.000000    3.500000    3.50000   
75%    325.000000   112.000000           4.000000    4.000000    4.00000   
max    340.000000   120.000000           5.000000    5.000000    5.00000   

             cgpa    research  chance_of_admit  
count  500.000000  500.000000        500.00000  
mean     8.576440    0.560000          0.72174  
std      0.604813    0.496884          0.14114  
min      6.800000    0.000000          0.34000  
25%      8.127500    0.000000          0.63000  
50%      8.560000    1.000000          0.72000  
75%      9.040000    1.000000          0.82000  
max      9.920000    1.000000          0.97000

In [8]:
df.duplicated().sum()

0

`univariate`

In [9]:
cols = df.columns.to_list()
cols, len(cols)

(['gre_score',
  'toefl_score',
  'university_rating',
  'sop',
  'lor',
  'cgpa',
  'research',
  'chance_of_admit'],
 8)

In [10]:
px.histogram(df,x=cols[0],text_auto=True)

In [11]:
px.box(df,x=cols[0])

In [12]:
px.histogram(df,x=cols[1],text_auto=True)

In [13]:
px.box(df,x=cols[1])

In [14]:
px.histogram(df,x=cols[2],text_auto=True)

In [15]:
px.box(df,x=cols[2])

In [16]:
px.histogram(df,x=cols[3],text_auto=True)

In [17]:
px.box(df,x=cols[3])

In [18]:
px.histogram(df,x=cols[4],text_auto=True)

In [19]:
px.box(df,x=cols[4])

In [20]:
px.histogram(df,x=cols[5],text_auto=True)

In [21]:
px.box(df,x=cols[5])

In [22]:
px.histogram(df,x=cols[7],text_auto=True)

In [23]:
px.box(df,x=cols[7])

`cat`

In [24]:
fig = go.Figure(data=[go.Pie(labels=df[cols[6]], hole=0.3,textinfo='percent+label')])
fig.update_traces(textposition='inside')

`bi variante`

`num vs num`

In [25]:
df.corr()

gre_score  toefl_score  university_rating       sop  \
gre_score           1.000000     0.827200           0.635376  0.613498   
toefl_score         0.827200     1.000000           0.649799  0.644410   
university_rating   0.635376     0.649799           1.000000  0.728024   
sop                 0.613498     0.644410           0.728024  1.000000   
lor                 0.524679     0.541563           0.608651  0.663707   
cgpa                0.825878     0.810574           0.705254  0.712154   
research            0.563398     0.467012           0.427047  0.408116   
chance_of_admit     0.810351     0.792228           0.690132  0.684137   

                        lor      cgpa  research  chance_of_admit  
gre_score          0.524679  0.825878  0.563398         0.810351  
toefl_score        0.541563  0.810574  0.467012         0.792228  
university_rating  0.608651  0.705254  0.427047         0.690132  
sop                0.663707  0.712154  0.408116         0.684137  
lor                1.000000  0.637469  0.372526         0.645365  
cgpa               0.637469  1.000000  0.501311         0.882413  
research           0.372526  0.501311  1.000000         0.545871  
chance_of_admit    0.645365  0.882413  0.545871         1.000000

In [26]:
px.imshow(df.corr(),text_auto='.2f')

In [27]:
px.scatter(df,x=cols[0],y=cols[-1])

In [28]:
px.scatter(df,x=cols[1],y=cols[-1])

In [29]:
px.scatter(df,x=cols[2],y=cols[-1])

In [30]:
px.scatter(df,x=cols[3],y=cols[-1])

In [31]:
px.scatter(df,x=cols[4],y=cols[-1])

In [32]:
px.scatter(df,x=cols[5],y=cols[-1])

`num vs cat`

In [33]:
px.box(df,y=cols[-1], x=cols[6])

In [34]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
X,y

(array([[337.  , 118.  ,   4.  , ...,   4.5 ,   9.65,   1.  ],
        [324.  , 107.  ,   4.  , ...,   4.5 ,   8.87,   1.  ],
        [316.  , 104.  ,   3.  , ...,   3.5 ,   8.  ,   1.  ],
        ...,
        [330.  , 120.  ,   5.  , ...,   5.  ,   9.56,   1.  ],
        [312.  , 103.  ,   4.  , ...,   5.  ,   8.43,   0.  ],
        [327.  , 113.  ,   4.  , ...,   4.5 ,   9.04,   0.  ]]),
 array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
        0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.65, 0.63, 0.62, 0.64, 0.7 ,
        0.94, 0.95, 0.97, 0.94, 0.76, 0.44, 0.46, 0.54, 0.65, 0.74, 0.91,
        0.9 , 0.94, 0.88, 0.64, 0.58, 0.52, 0.48, 0.46, 0.49, 0.53, 0.87,
        0.91, 0.88, 0.86, 0.89, 0.82, 0.78, 0.76, 0.56, 0.78, 0.72, 0.7 ,
        0.64, 0.64, 0.46, 0.36, 0.42, 0.48, 0.47, 0.54, 0.56, 0.52, 0.55,
        0.61, 0.57, 0.68, 0.78, 0.94, 0.96, 0.93, 0.84, 0.74, 0.72, 0.74,
        0.64, 0.44, 0.46, 0.5 , 0.96, 0.92, 0.92, 0.94, 0.76, 0.72, 0.66,
        0.64, 0

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [36]:
X_train

array([[318.  , 106.  ,   3.  , ...,   3.  ,   8.65,   0.  ],
       [308.  , 104.  ,   2.  , ...,   3.  ,   8.07,   0.  ],
       [311.  , 104.  ,   3.  , ...,   3.5 ,   8.13,   1.  ],
       ...,
       [306.  , 106.  ,   2.  , ...,   2.5 ,   8.14,   0.  ],
       [305.  , 112.  ,   3.  , ...,   3.5 ,   8.65,   0.  ],
       [311.  , 101.  ,   2.  , ...,   3.5 ,   8.34,   1.  ]])

In [44]:
# Define models to evaluate
models = {
    'Linear Regression': LinearRegression(),
    'Random Forest': RandomForestRegressor(),
    'Support Vector Machine': SVR(),
    'Decision Tree': DecisionTreeRegressor(),
    'K-Nearest Neighbors': KNeighborsRegressor()
}

# Define hyperparameters for each model
params = {
    'Linear Regression': {
        'regressor__normalize': [True, False]
    },
    'Random Forest': {
        'regressor__n_estimators': [100, 200, 300]
    },
    'Support Vector Machine': {'regressor__kernel': ['linear', 'rbf'], 'regressor__C': [0.1, 1, 10]},
    'Decision Tree': {'regressor__max_depth': [None, 5, 10]},
    'K-Nearest Neighbors': {'regressor__n_neighbors': [3, 5, 7]}
}

# Perform model selection and evaluation
results = {}
for model_name, model in models.items():
    # Construct a pipeline with scaler and regressor
    pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('regressor', model)
    ])
    
    # Perform hyperparameter tuning with cross-validation
    grid_search = GridSearchCV(pipeline, params[model_name], cv=5, scoring='neg_mean_squared_error', verbose=1)
    grid_search.fit(X_train, y_train)
    
    # Store results
    results[model_name] = {
        'Best Parameters': grid_search.best_params_,
        'Best Score': -grid_search.best_score_
    }

    # Perform cross-validation to estimate performance
    cv_scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')
    results[model_name]['CV Scores'] = -cv_scores  # Convert back to positive MSE

# Print results
for model_name, result in results.items():
    print(f"Model: {model_name}")
    print(f"Best Parameters: {result['Best Parameters']}")
    print(f"Best Score (MSE): {result['Best Score']}")
    print(f"Cross-Validation Scores (MSE): {result['CV Scores']}")
    print(f"Average Cross-Validation Score (MSE): {np.mean(result['CV Scores'])}\n")

# Select the best model based on average cross-validation score
best_model_name = min(results, key=lambda x: np.mean(results[x]['CV Scores']))
best_model = models[best_model_name]

# Train the best model on the full training data
best_model.fit(X_train, y_train)

# Evaluate the best model on the testing data
y_pred = best_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error on Testing Data: {mse}")
print(r2_score(y_test, y_pred))

Fitting 5 folds for each of 2 candidates, totalling 10 fits
Fitting 5 folds for each of 3 candidates, totalling 15 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  15 out of  15 | elapsed:    4.3s finished


Fitting 5 folds for each of 6 candidates, totalling 30 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Fitting 5 folds for each of 3 candidates, totalling 15 fits
Fitting 5 folds for each of 3 candidates, totalling 15 fits
Model: Linear Regression
Best Parameters: {'regressor__normalize': False}
Best Score (MSE): 0.0036829939181392117
Cross-Validation Scores (MSE): [0.00339408 0.00456161 0.00374138 0.00410143 0.00261647]
Average Cross-Validation Score (MSE): 0.0036829939181392117

Model: Random Forest
Best Parameters: {'regressor__n_estimators': 200}
Best Score (MSE): 0.004235164125000003
Cross-Validation Scores (MSE): [0.0038392  0.00506502 0.00397261 0.00401129 0.00426777]
Average Cross-Validation Score (MSE): 0.004231181974999998

Model: Support Vector Machine
Best Parameters: {'regressor__C': 0.1, 'regressor__kernel': 'linear'}
Best Score (MSE): 0.004521407804706616
Cross-Validation Scores (MSE): [0.00479798 0.00679127 0.00441971 0.00622889 0.00589808]
Average Cross-Validation Score (MSE): 0.005627185157750495

Model: Decision Tree
Best Parameters: {'regressor__max_depth': 5}
Best S

[Parallel(n_jobs=1)]: Done  30 out of  30 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  15 out of  15 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  15 out of  15 | elapsed:    0.0s finished


In [45]:
best_model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [46]:
print(r2_score(y_test, y_pred))

0.8188432567829634
