In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Lasso, Ridge,ElasticNet
from sklearn.tree import  DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split,cross_val_score,GridSearchCV
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.pipeline import Pipeline
import plotly.graph_objects as go
import xgboost as xgb
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('./Admission_Predict_Ver1.1.csv')
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [ ]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   serial_no.         500 non-null    int64  
 1   gre_score          500 non-null    int64  
 2   toefl_score        500 non-null    int64  
 3   university_rating  500 non-null    int64  
 4   sop                500 non-null    float64
 5   lor                500 non-null    float64
 6   cgpa               500 non-null    float64
 7   research           500 non-null    int64  
 8   chance_of_admit    500 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB


In [ ]:
df.drop('serial_no.',axis=1,inplace=True)

In [ ]:
df.head()

gre_score  toefl_score  university_rating  sop  lor  cgpa  research  \
0        337          118                  4  4.5  4.5  9.65         1   
1        324          107                  4  4.0  4.5  8.87         1   
2        316          104                  3  3.0  3.5  8.00         1   
3        322          110                  3  3.5  2.5  8.67         1   
4        314          103                  2  2.0  3.0  8.21         0   

   chance_of_admit  
0             0.92  
1             0.76  
2             0.72  
3             0.80  
4             0.65

In [ ]:
df.describe()

gre_score  toefl_score  university_rating         sop        lor  \
count  500.000000   500.000000         500.000000  500.000000  500.00000   
mean   316.472000   107.192000           3.114000    3.374000    3.48400   
std     11.295148     6.081868           1.143512    0.991004    0.92545   
min    290.000000    92.000000           1.000000    1.000000    1.00000   
25%    308.000000   103.000000           2.000000    2.500000    3.00000   
50%    317.000000   107.000000           3.000000    3.500000    3.50000   
75%    325.000000   112.000000           4.000000    4.000000    4.00000   
max    340.000000   120.000000           5.000000    5.000000    5.00000   

             cgpa    research  chance_of_admit  
count  500.000000  500.000000        500.00000  
mean     8.576440    0.560000          0.72174  
std      0.604813    0.496884          0.14114  
min      6.800000    0.000000          0.34000  
25%      8.127500    0.000000          0.63000  
50%      8.560000    1.000000          0.72000  
75%      9.040000    1.000000          0.82000  
max      9.920000    1.000000          0.97000

In [ ]:
df.duplicated().sum()

0

`univariate`

In [ ]:
cols = df.columns.to_list()
cols, len(cols)

(['gre_score',
  'toefl_score',
  'university_rating',
  'sop',
  'lor',
  'cgpa',
  'research',
  'chance_of_admit'],
 8)

In [ ]:
px.histogram(df,x=cols[0],text_auto=True)

In [ ]:
px.box(df,x=cols[0])

In [ ]:
px.histogram(df,x=cols[1],text_auto=True)

In [ ]:
px.box(df,x=cols[1])

In [ ]:
px.histogram(df,x=cols[2],text_auto=True)

In [ ]:
px.box(df,x=cols[2])

In [ ]:
px.histogram(df,x=cols[3],text_auto=True)

In [ ]:
px.box(df,x=cols[3])

In [ ]:
px.histogram(df,x=cols[4],text_auto=True)

In [ ]:
px.box(df,x=cols[4])

In [ ]:
px.histogram(df,x=cols[5],text_auto=True)

In [ ]:
px.box(df,x=cols[5])

In [ ]:
px.histogram(df,x=cols[7],text_auto=True)

In [ ]:
px.box(df,x=cols[7])

`cat`

In [ ]:
fig = go.Figure(data=[go.Pie(labels=df[cols[6]], hole=0.3,textinfo='percent+label')])
fig.update_traces(textposition='inside')

`bi variante`

`num vs num`

In [ ]:
df.corr()

gre_score  toefl_score  university_rating       sop  \
gre_score           1.000000     0.827200           0.635376  0.613498   
toefl_score         0.827200     1.000000           0.649799  0.644410   
university_rating   0.635376     0.649799           1.000000  0.728024   
sop                 0.613498     0.644410           0.728024  1.000000   
lor                 0.524679     0.541563           0.608651  0.663707   
cgpa                0.825878     0.810574           0.705254  0.712154   
research            0.563398     0.467012           0.427047  0.408116   
chance_of_admit     0.810351     0.792228           0.690132  0.684137   

                        lor      cgpa  research  chance_of_admit  
gre_score          0.524679  0.825878  0.563398         0.810351  
toefl_score        0.541563  0.810574  0.467012         0.792228  
university_rating  0.608651  0.705254  0.427047         0.690132  
sop                0.663707  0.712154  0.408116         0.684137  
lor                1.000000  0.637469  0.372526         0.645365  
cgpa               0.637469  1.000000  0.501311         0.882413  
research           0.372526  0.501311  1.000000         0.545871  
chance_of_admit    0.645365  0.882413  0.545871         1.000000

In [ ]:
px.imshow(df.corr(),text_auto='.2f')

In [ ]:
px.scatter(df,x=cols[0],y=cols[-1])

In [ ]:
px.scatter(df,x=cols[1],y=cols[-1])

In [ ]:
px.scatter(df,x=cols[2],y=cols[-1])

In [ ]:
px.scatter(df,x=cols[3],y=cols[-1])

In [ ]:
px.scatter(df,x=cols[4],y=cols[-1])

In [ ]:
px.scatter(df,x=cols[5],y=cols[-1])

`num vs cat`

In [ ]:
px.box(df,y=cols[-1], x=cols[6])

In [ ]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
X,y

(array([[337.  , 118.  ,   4.  , ...,   4.5 ,   9.65,   1.  ],
        [324.  , 107.  ,   4.  , ...,   4.5 ,   8.87,   1.  ],
        [316.  , 104.  ,   3.  , ...,   3.5 ,   8.  ,   1.  ],
        ...,
        [330.  , 120.  ,   5.  , ...,   5.  ,   9.56,   1.  ],
        [312.  , 103.  ,   4.  , ...,   5.  ,   8.43,   0.  ],
        [327.  , 113.  ,   4.  , ...,   4.5 ,   9.04,   0.  ]]),
 array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
        0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.65, 0.63, 0.62, 0.64, 0.7 ,
        0.94, 0.95, 0.97, 0.94, 0.76, 0.44, 0.46, 0.54, 0.65, 0.74, 0.91,
        0.9 , 0.94, 0.88, 0.64, 0.58, 0.52, 0.48, 0.46, 0.49, 0.53, 0.87,
        0.91, 0.88, 0.86, 0.89, 0.82, 0.78, 0.76, 0.56, 0.78, 0.72, 0.7 ,
        0.64, 0.64, 0.46, 0.36, 0.42, 0.48, 0.47, 0.54, 0.56, 0.52, 0.55,
        0.61, 0.57, 0.68, 0.78, 0.94, 0.96, 0.93, 0.84, 0.74, 0.72, 0.74,
        0.64, 0.44, 0.46, 0.5 , 0.96, 0.92, 0.92, 0.94, 0.76, 0.72, 0.66,
        0.64, 0

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [ ]:
X_train

array([[321.  , 111.  ,   3.  , ...,   4.  ,   8.83,   1.  ],
       [316.  , 111.  ,   4.  , ...,   5.  ,   8.54,   0.  ],
       [303.  , 102.  ,   3.  , ...,   3.  ,   8.5 ,   0.  ],
       ...,
       [302.  ,  99.  ,   1.  , ...,   2.  ,   7.25,   0.  ],
       [309.  , 105.  ,   2.  , ...,   4.  ,   7.68,   0.  ],
       [314.  , 106.  ,   2.  , ...,   3.5 ,   8.25,   0.  ]])

In [ ]:
# Define models to evaluate
models = {
    'Linear Regression': LinearRegression(),
    'Random Forest': RandomForestRegressor(),
    'Support Vector Machine': SVR(),
    'Decision Tree': DecisionTreeRegressor(),
    'K-Nearest Neighbors': KNeighborsRegressor(),
    'XGBoost':xgb.XGBRegressor()
}

# Define hyperparameters for each model
params = {
    'Linear Regression': {
    },
    'Random Forest': {
        'regressor__n_estimators': [100, 200, 300],
        'regressor__max_depth': [None, 5, 10]
    },
    'Support Vector Machine': {'regressor__kernel': ['linear', 'rbf'], 'regressor__C': [0.1, 1, 10]},
    'Decision Tree': {'regressor__max_depth': [None, 5, 10]},
    'K-Nearest Neighbors': {'regressor__n_neighbors': [3, 5, 7]},
    'XGBoost': {
        'regressor__n_estimators': [100, 200, 300],
        'regressor__learning_rate': [0.05, 0.1, 0.2],
        'regressor__max_depth': [3, 4, 5]
    }
}

# Perform model selection and evaluation
results = {}
for model_name, model in models.items():
    # Construct a pipeline with scaler and regressor
    pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('regressor', model)
    ])
    print(model_name)
    # Perform hyperparameter tuning with cross-validation
    grid_search = GridSearchCV(pipeline, params[model_name], cv=5, scoring='neg_mean_squared_error', verbose=1)
    grid_search.fit(X_train, y_train)

    # Store results
    results[model_name] = {
        'Best Parameters': grid_search.best_params_,
        'Best Score': -grid_search.best_score_
    }

    # Perform cross-validation to estimate performance
    cv_scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')
    results[model_name]['CV Scores'] = -cv_scores  # Convert back to positive MSE

# Print results
for model_name, result in results.items():
    print(f"Model: {model_name}")
    print(f"Best Parameters: {result['Best Parameters']}")
    print(f"Best Score (MSE): {result['Best Score']}")
    print(f"Cross-Validation Scores (MSE): {result['CV Scores']}")
    print(f"Average Cross-Validation Score (MSE): {np.mean(result['CV Scores'])}\n")

# Select the best model based on average cross-validation score
best_model_name = min(results, key=lambda x: np.mean(results[x]['CV Scores']))
best_model = models[best_model_name]

# Train the best model on the full training data
best_model.fit(X_train, y_train)

# Evaluate the best model on the testing data
y_pred = best_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error on Testing Data: {mse}")
print(r2_score(y_test, y_pred))

Linear Regression
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Random Forest
Fitting 5 folds for each of 9 candidates, totalling 45 fits
Support Vector Machine
Fitting 5 folds for each of 6 candidates, totalling 30 fits
Decision Tree
Fitting 5 folds for each of 3 candidates, totalling 15 fits
K-Nearest Neighbors
Fitting 5 folds for each of 3 candidates, totalling 15 fits
XGBoost
Fitting 5 folds for each of 27 candidates, totalling 135 fits
Model: Linear Regression
Best Parameters: {}
Best Score (MSE): 0.0036829939181392117
Cross-Validation Scores (MSE): [0.00339408 0.00456161 0.00374138 0.00410143 0.00261647]
Average Cross-Validation Score (MSE): 0.0036829939181392117

Model: Random Forest
Best Parameters: {'regressor__max_depth': 5, 'regressor__n_estimators': 200}
Best Score (MSE): 0.004141738967267172
Cross-Validation Scores (MSE): [0.00378823 0.00498573 0.00386834 0.00406247 0.00438411]
Average Cross-Validation Score (MSE): 0.004217775399999997

Model: Support Vector M

In [ ]:
best_model

LinearRegression()

In [ ]:
print(r2_score(y_test, y_pred))

0.8188432567829632


In [ ]:
X.shape

(500, 7)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense
ann = Sequential()
ann.add(Dense(8,activation='relu',input_dim=7))
ann.add(Dense(16,activation='relu'))
ann.add(Dense(1,activation='linear'))
ann.compile(loss='mean_squared_error',optimizer='Adam')
history = ann.fit(X_train,y_train,epochs=100,validation_split=0.2)
r2_score(y_test,y_pred)

Epoch 1/100
10/10 [==============================] - 2s 53ms/step - loss: 533.4423 - val_loss: 399.2165
Epoch 2/100
10/10 [==============================] - 0s 10ms/step - loss: 303.2839 - val_loss: 222.2805
Epoch 3/100
10/10 [==============================] - 0s 7ms/step - loss: 165.9899 - val_loss: 120.2307
Epoch 4/100
10/10 [==============================] - 0s 6ms/step - loss: 88.7125 - val_loss: 64.1834
Epoch 5/100
10/10 [==============================] - 0s 7ms/step - loss: 46.7664 - val_loss: 34.0540
Epoch 6/100
10/10 [==============================] - 0s 8ms/step - loss: 24.4391 - val_loss: 17.8893
Epoch 7/100
10/10 [==============================] - 0s 7ms/step - loss: 12.5628 - val_loss: 9.2781
Epoch 8/100
10/10 [==============================] - 0s 5ms/step - loss: 6.3268 - val_loss: 4.7901
Epoch 9/100
10/10 [==============================] - 0s 8ms/step - loss: 3.1890 - val_loss: 2.5206
Epoch 10/100
10/10 [==============================] - 0s 5ms/step - loss: 1.6429 - val_l

0.8188432567829632